export const carsaction = {
    LOAD: 'CARS_LOAD',
    LOAD_SUCCESS : 'CARS_LOAD_SUCCESS',
    LOAD_FAILURE : 'CARS_LOAD_FAILURE',
    AUTH_LOAD : 'AUTH_LOAD',
    LOGIN: 'LOGIN',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    LOGOUT: 'LOGOUT'
}
